language: node_js
cache:
  directories:
  - node_modules
services:
  - docker
notifications:
  email: false
node_js:
- '8.11.3'
install: true
script:
  - docker build -t luislhl/staticman .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branches:
      only:
      - /.*/